name: 'setup-goplus'
description: 'Setup a Go+ environment and add it to the PATH'
icon-badge: 'arrow-up-circle'
color: 'blue'
author: 'GoPlus Team'
inputs:
  gop-version:
    description:
      'The Go+ version to download (if necessary) and use. Supports semver spec
      and ranges. Be sure to enclose this option in single quotation marks.'
  gop-version-file:
    description: 'Path to the gop.mod or gop.work file.'
  go-version:
    description:
      'The Go version to download (if necessary) and use. Supports semver spec
      and ranges. Be sure to enclose this option in single quotation marks.'
  go-version-file:
    description: 'Path to the go.mod or go.work file.'
  check-latest:
    description:
      'Set this option to true if you want the action to always check for the
      latest available version that satisfies the version spec'
    default: false
  token:
    description:
      Used to pull Go distributions from go-versions. Since there's a default,
      this is typically not supplied by the user. When running this action on
      github.com, the default value is sufficient. When running on GHES, you can
      pass a personal access token for github.com if you are experiencing rate
      limiting.
    default:
      ${{ github.server_url == 'https://github.com' && github.token || '' }}
  cache:
    description:
      Used to specify whether caching is needed. Set to true, if you'd like to
      enable caching.
    default: true
  cache-dependency-path:
    description: 'Used to specify the path to a dependency file - go.sum'
  architecture:
    description:
      'Target architecture for Go to use. Examples: x86, x64. Will use system
      architecture by default.'
outputs:
  gop-version:
    description:
      'The installed Go+ version. Useful when given a version range as input.'
  go-version:
    description:
      'The installed Go version. Useful when given a version range as input.'
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit'
runs:
  using: 'composite'
  steps:
    - uses: 'actions/setup-go@v4'
    - name: 'Setup Go+'
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
