name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          go-version: '1.21.0'
          gop-version: '1.1.7'

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.gop-version }}"

  test-versions:
    name: Gop Versions Test

    strategy:
      matrix:
        gop-version: ['1.1.7', '', 'latest', 'main', 'v1.0']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Gop Version
        id: test-gop-version
        uses: ./
        with:
          gop-version: ${{ matrix.gop-version }}

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.test-gop-version.outputs.gop-version }}"
          if [[ "{{ matrix.gop-version }}" == "1.1.7" ]]; then
            if [[ "${{ steps.test-gop-version.outputs.gop-version-verified }}" != "true" ]]; then
              echo "Expected version 1.1.7 to be verified"
              exit 1
            fi
          else
            if [[ "${{ steps.test-gop-version.outputs.gop-version-verified }}" == "true" ]]; then
              echo "Expected version 1.1.7 to not be verified"
              exit 1
            fi
          fi
